print(len(str((12345))))
print(type("Hello"))
print(type(123))
print(type(1.1))
print(type(True))
print(int("123") + int("456"))
print("Number of letters in your name: " + str(len(input("Enter your name: "))))